version: '3'
services:
  web:
    build: .
    image: recipicker
    ports:
      - 80:80
    environment:
      - PORT=80
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    volumes:
      - ./log:/app/log
