version: '3'
services:
  web:
    build:
      context: .
      args:
        - RAILS_ENV=${RAILS_ENV}
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    image: recipicker
    ports:
      - 80:80
    environment:
      - PORT=80
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - ./log:/app/log
